### ISSUE TITLE
[Problem Executing the Project] (Ubuntu 20.04) The extracting bg problem in "bot_localization.py".

### ISSUE THREAD

**Issue by SteveT7321** [HaiderAbasi/ROS2-Path-Planning-and-Maze-Solving#5]
### Prerequisites

* [ y ] Are you running the latest version (Repo)?
* [ y ] Did you follow the How_to_Run_the_project guide in Section 1 (Lec 1 & 2)?
* [ y ] Did you check Issues on Github for related queries?
* [ y ] Did you try restarting the PC and re-doing the steps in Section 1 (Lec 1 & 2)?
* [ y ] Is the problem persistent?

### Description
Hi !
I'm in the step of localization (bot_localization.py).
I create a simple world (4 walls only) and try to extract the backgroung model ,but comes with this error.

The camera is working but the variable "min_cntr_idx" is -1,  seems that the function "ret_smallest_obj" does not work...
How can I deal with this error?
Should I move the camera or modify the functions in utilities.py?
Thank you for help!
![Screenshot from 2022-08-18 16-25-39](https://user-images.githubusercontent.com/82607704/185349374-ef558d50-8027-4956-bac2-b290ddde847e.png)
![Screenshot from 2022-08-18 16-25-45](https://user-images.githubusercontent.com/82607704/185349388-ba27180d-6d74-4272-a1bc-89b41b7f7aa2.png)

### Steps to Reproduce

1. Launch the word(maze)
2. Run "maze_solver.py" 

**Expected behavior:** 
The frame "frame_car_remvd" should be showed.

**Actual behavior:** 
Comes in error:
UnboundLocalError: local variable 'frame_car_remvd' referenced before assignment

**Screenshots**
![Screenshot from 2022-08-18 15-59-59](https://user-images.githubusercontent.com/82607704/185343694-a51e7003-5334-49b1-bb2f-cdd2478b4f4e.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - OS-Version: 20.04 LTS
 - Python-Version: 3.8.10
 - OpenCV-Version: 4.2.0

**Hardware**
- Desktop
- CPU: AMD Ryzen 5 5600X
- GPU: Nvidia RTX 3060
- RAM: 16G

**Comment by HaiderAbasi** [comment]
- Add these lines of code to **bot_localization.py** then **share the Screenshots,** here.
   (So that we could see if rois_mask and edges were computed correctly or not.)
```
# Debugging: Checking to see if results of edges and rois_mask are as required or not
cv2.imshow("edges",edges)
cv2.imshow("rois_mask",rois_mask)
cv2.waitKey(0)
```
![issue](https://user-images.githubusercontent.com/49869365/185374509-37715666-536c-415b-a8bd-64764dfadf3f.png)

**Comment by SteveT7321** [comment]
Hi! Thanks for replying! 
These are the results I got.
![Screenshot from 2022-08-18 20-52-19](https://user-images.githubusercontent.com/82607704/185399391-2db7ac2b-301e-431c-baee-f183a9a3b65b.png)

![Screenshot from 2022-08-18 20-52-29](https://user-images.githubusercontent.com/82607704/185399414-cd3b38fa-65b9-42b5-9a1b-814ab905dedb.png)

![Screenshot from 2022-08-18 20-52-34](https://user-images.githubusercontent.com/82607704/185399427-94be0d4c-d86e-49fd-9728-4a42527c23c4.png)

**Comment by HaiderAbasi** [comment]
Alright! I understand the problem.

> I should have been **more explicit with project constraints**. Anyways I will **list them here** for everyone. 


**1.**  **Maze needs one entry and one exit.** 

-  **Method:** Remove one portion of the wall (at least twice car width) from the left side where you want your exit
    and one from the right side where you have your car as a maze entry

-  **Reason:** _extractbgmodel()_ is set up like this. For a closed maze **(like the above example)** it will result in ignoring everything inside. **(Which we do not want!)**

**2.**  **Entry point can only be on the right side wall.**

-  **Reason:** Primarily because the mapping module at the moment only looks at the right side for the maze entry point

**3.**  **There should be at least one path to the maze exit**

-  **Reason:**  Path planning algorithm is assuming a path to be present. Don;t want to disappoint it :)

**Comment by HaiderAbasi** [comment]
**Suggestions:** If you still want to solve the maze in the following circumstance


> **Closed Maze.** Entry is selected based on the car's location and destination manually selected by user. In this case. You will need to modify the following modules. 

**a) Localization:** adjust extractbgmodel() to find only the mask of ROIs. 
-  **(Hint: Investigate contour hierarchy)**

**b) Mapping:** Modify the start and end point of the map, before the creation of the graph. 
- **(Hint: Start can be based on cars location extraction in Localization module, End can be manually taken from the user using cv2.selectROI)**


> **Open Maze but entry point not restricted to right wall** 

**a) Localization:** adjust extractbgmodel() but this time it rotates to keep which side the car is closest to at the bottom
-  **(Hint: Find the closest maze wall to the car. Provide the necessary angle to cv2,rotate so that wall becomes the base in the maze occupancy grid)**

> **Side Note:** Interested developers are open to checking out **how I used the robot-navigation algorithm I developed in this repo.** Modified it a little to **act as a Satellite Navigation System for the Self Driving Car.**
- @SteveT7321  You too can check it out **it's available on Github**. 
[**Repo**](https://github.com/noshluk2/ROS2-Self-Driving-Car-AI-using-OpenCV)
[**Sat-Nav (Gif):**](https://github.com/noshluk2/ROS2-Self-Driving-Car-AI-using-OpenCV/blob/main/Images_videos/Sat_Nav/4_motionplanning.gif)
[**Guide to Test it Yourself:**](https://github.com/noshluk2/ROS2-Self-Driving-Car-AI-using-OpenCV/blob/main/self_driving_car_pkg/self_driving_car_pkg/Guide_to_run_Sat-Nav_on_SDC.md)
**There might be suggestions on modifying it for your case if you like.**

**Comment by HaiderAbasi** [comment]
Issue is being closed due to inactivity.

Anyone facing similar problem, 
**Refer to the constraints regarding building the maze.**
( mentioned in the previous comment )
